### ISSUE TITLE
Scheduler-card not visible in "ADD CARD" menu

### ISSUE THREAD

**Issue by vescherry** [nielsfaber/scheduler-card#626] opened 2022-11-20 07:51 UTC
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.12

### Bug description

Scheduler-card not visible in "ADD CARD" menu. I downloaded this component from HACS, restarted and installed and added the integration. I want to add it to the dashboard but the scheduler-card is not visible.

### Steps to reproduce

I deleted and reinstalled the integration several times but it has no effect.
  A config/custom_components/scheduler folder has been created.

### Additional info

Home Assistant 2022.11.3
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest
Windows 10, Virtual box instalation.

**Comment by nielsfaber** [comment] 2022-11-20 07:54
Duplicate of #624

**Closed by nielsfaber** 2022-11-20 07:54 UTC
Labels: bug

**Comment by nielsfaber** [comment] 2022-11-22 04:39
Since multiple users reported issues with upgrading to v2.3.8, I decided to make a new release v2.3.9 which doesn't have any changes but hopefully solves the updating via HACS.
