### ISSUE TITLE
Use binary_sensor in conditions

### ISSUE THREAD

**Issue by q1x** [nielsfaber/scheduler-card#460] opened 2021-10-14 06:20 UTC
Hi, thanks for the great add-on!

I use binary sensors (templates) to calculate states within my home automation and I'd like to be able to use these as a condition in schedules.

Current workaround would be to add a virtual switch or input boolean that follows the state of the binary_sensor, but that feels clunky and unneeded.

### Checklist
- [ X ] I checked for similar existing requests (both open and closed) before posting.
- [ X ] My request is generic, other users may benefit from it too.

### Proposal
Ability to pick binary_sensors in schedule conditions.

### Additional info
N/A

**Comment by nielsfaber** [comment] 2021-11-07 06:31
Closing, assuming the issue is fixed.

**Closed by nielsfaber** 2021-11-07 06:31 UTC
Labels: bug, in development
