### ISSUE TITLE
Feature Request: run action only if someone (or no one) is at home

### ISSUE THREAD

**Issue by MatteGary** [nielsfaber/scheduler-card#44] opened 2020-09-16 20:12 UTC
It would be awesome to have the possibility to let an automation run if no one is at home, or if someone is at home, like Apple Home App let us do.

I have an automation in Apple Home App that basically is “If no one is at home at 19:00, then turn on my garden light”.

Option should be:
. Run if no one is at home 
. Run if someone is at home

**Comment by KTibow** [comment] 2020-09-16 20:13
Duplicate of #24

**Comment by nielsfaber** [comment] 2020-09-27 14:41
Closing -->  i put your request in the original topic

**Closed by nielsfaber** 2020-09-27 14:41 UTC
Labels: duplicate
