### ISSUE TITLE
At sunrise/sunset but no later than/not before

### ISSUE THREAD

**Issue by fschwarz86** [nielsfaber/scheduler-card#522] opened 2022-02-03 08:52 UTC
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Allow to set a "no later than/not before" for sunrise/sunset conditions.

### Additional info

"switch on lights at sunset, but no later than 6pm" or "open roller shutter at sunrise, but not before 7am".

**Comment by nielsfaber** [comment] 2022-02-05 06:31
>  I checked for similar existing requests (both open and closed) before posting.

It doesn't look that way.
Duplicate of #336 and #281.

If you create some time sensor or entity which is on in case it is earlier than 6pm, you can assign it as condition.

**Closed by nielsfaber** 2022-02-05 06:31 UTC
Labels: feature_request
