### ISSUE TITLE
Erros on Log - 'an integer is required (got type str)'

### ISSUE THREAD

**Issue by jonathanicq** [nielsfaber/scheduler-card#416] opened 2021-05-29 11:49 UTC
@nielsfaber 
I've receiving this following error even thought, It seems that is working fne.

21-05-29 11:45:07 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1275948' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)

**Comment by nielsfaber** [comment] 2021-05-29 11:53
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/411

**Closed by nielsfaber** 2021-05-29 11:53 UTC
