### ISSUE TITLE
Custom element doesn't exist: scheduler-card with newest update

### ISSUE THREAD

**Issue by TheTravelAddict** [nielsfaber/scheduler-card#627] opened 2022-11-21 19:34 UTC
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.8

### Component Version

v3.2.12

### Bug description

Installed Home Assistant core update this morning - and now card shows as missing: "Custom element doesn't exist: scheduler-card." on the dashboard.  
Tried deleting the scheduler integration, restarting HA, reinstalling the integration, and restarting HA again.  No change. 

### Steps to reproduce

Install newest and watch it fail.
Home Assistant Core 22.11.3
Home Assistant OS 9.3

**Comment by nielsfaber** [comment] 2022-11-21 19:40
>  I checked for similar existing issues (both open and closed) before posting.

you’re sure about this?

duplicate of https://github.com/nielsfaber/scheduler-card/issues/624

**Closed by nielsfaber** 2022-11-21 19:40 UTC
Labels: bug

**Comment by nielsfaber** [comment] 2022-11-22 04:39
Since multiple users reported issues with upgrading to v2.3.8, I decided to make a new release v2.3.9 which doesn't have any changes but hopefully solves the updating via HACS.

**Comment by TheTravelAddict** [comment] 2022-11-22 04:56
That fixed it.  All good now.  Dank u wel!
