### ISSUE TITLE
Feature request: "timer plans"

### ISSUE THREAD

**Issue by bikeymouse** [nielsfaber/scheduler-card#357] opened 2021-04-02 13:36 UTC
What we all probably have, is that we want to set our timer-schedules differently based on if we are have our regular working period, are from home for a short period or  away on vacation.

For that it would be nice if the Scheduler-card would have a "master-selector" indicating which "timer-plan" (e.g. "regular", "vacation", "away") is active. Depending on that master-switch you would then also only view/add and change schedules for that specific timer-plan. This will keep the amount of schedules in the overview nice and tidy as well.

Of course this can be made by adding additional conditions in each schedule, but you could not "filter" which ones are actually active.

**Comment by nielsfaber** [comment] 2021-04-02 13:58
Scheduler interfaces with the [workday integration](https://www.home-assistant.io/integrations/workday/) for this purpose.
If you set up your schedules for weekdays vs weekends, holidays are automatically taken into account and follow the same rules as weekends.
Otherwise, you can easily enable/disable a set of schedules for switching to a "holiday mode".

I don't see a need for adding more functionality than this.

**Comment by bikeymouse** [comment] 2021-04-02 14:15
Hmmm, I don't see how I can use the workday integration e.g. to select that I want to switch on my porch light every day during the "Holliday". Or only once a week. In the current set-up, one has to choose to either use a "workday" or select a day, while in fact you would like to combine those.

Also, there is no simple way to see which schedules do use the workday-condition, so which ones are relevant or not.

So I'm not asking to create the logic to determine what the workday's or holiday's are - which indeed can be done with the workday integration - but just a simple way to use that as a "master" switch to activate and then filter on only the "active" schedules.

**Comment by nielsfaber** [comment] 2021-04-02 14:31
To answer your questions:

> I don't see how I can use the workday integration e.g. to select that I want to switch on my porch light every day during the "Holliday".

My recommendation would be to make a specific schedule for defining the desired behaviour for the porch light during your holidays, and enable that one temporarily.
Alternatively, you could ofcourse temporarily modify the normal schedule for your porch light to the pattern that you're looking for.

> Or only once a week. In the current set-up, one has to choose to either use a "workday" or select a day, while in fact you would like to combine those.

You can choose your own set of days as well. So once per week or some custom set is not an issue.
A case like "workdays + sunday" is not possible no, but I also wonder about the practical use of such combination.

> Also, there is no simple way to see which schedules do use the workday-condition, so which ones are relevant or not.

You can say the same about all automations in HA. You will have to organise them yourself, for example by assigning a meaningful name to them.

> but just a simple way to use that as a "master" switch to activate and then filter on only the "active" schedules.

There is already an option for adding a master switch to the card. Look for `show_header_toggle`.
There are open requests for adding filter options to the overview page of the card, please give them your :+1: if you would like such functionality as well.

I am closing the issue as it is getting too much into a discussion.

Please take into account that this "scheduler card" is not meant to 'fill all the gaps' caused by the HA not having any scheduling functionality. 
I hope you can respect that I have a certain philosophy of what it should and shouldn't able to do (to prevent it from becoming too difficult to use).

**Closed by nielsfaber** 2021-04-02 14:31 UTC

**Comment by bikeymouse** [comment] 2021-04-02 14:39
Ok, thanks for your answers. I'll give a thumbs-up for the filter option, that would already help a bit ;-)
