### ISSUE TITLE
"Add" button only shows for administrators/owners / No way for non-admin users to add schedules to card

### ISSUE THREAD

**Issue by yomotherboard** [nielsfaber/scheduler-card#361] opened 2021-04-09 07:48 UTC
I am finding that only owner/admin users can create schedules with this card on my hass. If this is not a bug, I think it takes a way a huge use case of this card. I intend to use this to give my parents a way to create schedules, without exposing them to the clutter and confusion of the administrative controls on home assistant. Thanks to all for the great work!

**Comment by nielsfaber** [comment] 2021-04-09 08:01
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/282

**Closed by nielsfaber** 2021-04-09 08:01 UTC
