### ISSUE TITLE
Card disappears from Lovelace after adding a schedule

### ISSUE THREAD

**Issue by cherokee93** [nielsfaber/scheduler-card#532] opened 2022-02-15 13:47 UTC
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.3

### Component Version

3.2.7

### Bug description

Crash when adding new schedule.

### Steps to reproduce

Press add schedule button

### Additional info

Related to https://github.com/nielsfaber/scheduler-card/issues/440#issue-986277093

Here is the card config:

```
type: custom:scheduler-card
title: Programmi
include:
  - light
  - switch
  - group
time_step: 5
```
Here is the chrome's console log:

```
light-entity-card.js:1478 
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at f.trim (light-entity-card.js:1478:27)
    at t.exports (light-entity-card.js:3243:21)
    at c (scheduler-card.js?hacstag=286270157232:179:5035)
    at bs (scheduler-card.js?hacstag=286270157232:179:5091)
    at Fs (scheduler-card.js?hacstag=286270157232:179:23301)
    at scheduler-card.js?hacstag=286270157232:179:22525
    at Array.forEach (<anonymous>)
    at Us (scheduler-card.js?hacstag=286270157232:179:22417)
```
It hangs the page and the only fix is to CTRL+F5

Here is the video of it happening:

https://user-images.githubusercontent.com/12370126/154074457-c6f99fb7-67f1-48e4-9a98-6b3430086dc4.mp4

**Comment by nielsfaber** [comment] 2022-03-05 16:43
Your bug report is a duplicate of https://github.com/nielsfaber/scheduler-card/issues/440 (not just related, exactly the same issue).
This bug is caused by the light-entity-card, I cannot fix that.
Please report to the maintainer of that card.

**Closed by nielsfaber** 2022-03-05 16:43 UTC
Labels: bug

**Comment by cherokee93** [comment] 2022-03-05 17:02
Awesome, now I know what the problem is and how to be able to use your precious card again. Thanks! 
I'll check issues of light-entity-card then.
