### ISSUE TITLE
Conditions not always applied?

### ISSUE THREAD

**Issue by derandiunddasbo** [nielsfaber/scheduler-card#351] opened 2021-03-23 18:47 UTC
I defined two schedules with four time slots...

![image](https://user-images.githubusercontent.com/15999980/112196062-ed13ee00-8c0a-11eb-93b4-306718883982.png)

...and a condition checking a binary sensor...

![image](https://user-images.githubusercontent.com/15999980/112196294-2cdad580-8c0b-11eb-8205-bf21e1ff4b91.png)

(Yes, there is a reason for setting the same HVAC preset twice a day, because the preset is also changed by other schedules and automations but should be re-set at noon if changed sometimes in the morning.)

The Problem: The schedule at 12:05:00 is still triggered, even if the condition is false.

I think, the reason for this is, that the defined condition is missing in the third time slot of this schedule ("start": "12:05:00", "stop": "21:00:00") in scheduler.storage:
 

```
[...]
            {
                "schedule_id": "a572f8",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "05:30:00",
                        "conditions": [
                            {
                                "entity_id": "binary_sensor.heizung_modus_kinder",
                                "attribute": "state",
                                "value": "on",
                                "match_type": "is"
                            }
                        ],
                        "condition_type": "or",
                        "actions": [
                            {
                                "service": "climate.set_preset_mode",
                                "entity_id": "climate.og_bad_raumregler",
                                "service_data": {
                                    "preset_mode": "sleep"
                                }
                            }
                        ]
                    },
                    {
                        "start": "05:30:00",
                        "stop": "12:05:00",
                        "conditions": [
                            {
                                "entity_id": "binary_sensor.heizung_modus_kinder",
                                "attribute": "state",
                                "value": "on",
                                "match_type": "is"
                            }
                        ],
                        "condition_type": "or",
                        "actions": [
                            {
                                "service": "climate.set_preset_mode",
                                "entity_id": "climate.og_bad_raumregler",
                                "service_data": {
                                    "preset_mode": "comfort"
                                }
                            }
                        ]
                    },
                    {
                        "start": "12:05:00",
                        "stop": "21:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_preset_mode",
                                "entity_id": "climate.og_bad_raumregler",
                                "service_data": {
                                    "preset_mode": "comfort"
                                }
                            }
                        ]
                    },
                    {
                        "start": "21:00:00",
                        "stop": "00:00:00",
                        "conditions": [
                            {
                                "entity_id": "binary_sensor.heizung_modus_kinder",
                                "attribute": "state",
                                "value": "on",
                                "match_type": "is"
                            }
                        ],
                        "condition_type": "or",
                        "actions": [
                            {
                                "service": "climate.set_preset_mode",
                                "entity_id": "climate.og_bad_raumregler",
                                "service_data": {
                                    "preset_mode": "sleep"
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "",
                "enabled": true
            },
[...]
```

I don't know, if this s a scheduler-card issue or an issue with the scheduler integration, but the generated configuration seems to be wrong.

**Comment by nielsfaber** [comment] 2021-03-23 18:51
Woops that's a bug.
The scheduler-component allows each timeslot to have its own conditions, but in the scheduler-card they should always be applied to all slots.
There must be an issue caused by editing or adding a timeslot, where a previously created condition is not properly copied.
I will have to investigate this..

**Comment by derandiunddasbo** [comment] 2021-03-23 18:56
Ok, thanks for confirming. Until this is resolved, I'll manually add the two missing conditions to these schedulers and don't touch them in the scheduler-card. :-)

**Comment by nielsfaber** [comment] 2021-03-23 19:01
There's no harm in manually editing the file.
The only issue is that you will need to restart HA to have the changes applied.
If you can reproduce this issue, that would be helpful.
I'm curious what steps you did to end up with this situation.

**Comment by derandiunddasbo** [comment] 2021-03-24 20:03
Actually yes. After testing this a little further the problem boils down to scheduler-card not applying an existing condition to the new time slot after splitting an existing slot into two.

So to reproduce this:

1. Add a new scheduler
2. Chose an entity
3. Make Scheme > Next
4. Set Values for the existing three time slots (it's not necessary to change start / end times)
5. Open Options
6. Add any condition, Save
7. Save scheduler
8. Edit the same scheduler again
9. Select one of the time slots (i chose the middle one)
10. Add a new time slot (this splits up the selected slot into two)
11. Set a value for the new time slot
12. Save the scheduler

This leads to the condition _not_ being applied to the newly created slot in step 10.

Opening and re-saving the options for the scheduler (w/o changing them) doesn't apply the condition to the new slot.

But: If one of the conditions is changed or a new one is added, then these conditions are applied to all existing slots.

Thus, as a workaround it is necessary to actually _change_ any of the existing conditions after adding a new time slot in a scheduler to apply the conditions to all time slots. F.e. I changed the operator from "is" to "not", saved it, opened it again, reverted the operator back to "is" and saved again. After this procedure, the condition appears in all defined time slots.

**Comment by nielsfaber** [comment] 2021-03-24 21:48
Excellent investigation work!
You helped me [pin down](https://github.com/nielsfaber/scheduler-card/blob/42b53c399a160a4d3db22514a932d9ddabfd9d63/src/custom-elements/timeslot-editor.ts#L277) the issue to a single piece of code.
I will work on an update that should solve this issue.

**Comment by IsaacBreuer** [comment] 2021-04-06 04:19
wow, I had some strange behavior due to this bug, also in my case the condition missing was at the first time slot, and then the card just didn't display the condition at all... looks like the card regenerated based on first slot.. so the workaround of modifying condition from is to is not was not even possible,  I just edited the .storage file.
thanks for reporting

**Comment by nielsfaber** [comment] 2021-04-29 20:47
This should be fixed with the V2.1.0 release.
Please test it and close the issue if it’s indeed solved now.

**Comment by nielsfaber** [comment] 2021-05-08 12:54
Closing the issue, assuming the problem is solved.
If this is not the case, please let me know.

**Closed by nielsfaber** 2021-05-08 12:54 UTC
Labels: bug, in development

**Comment by hubikj** [comment] 2022-01-11 23:24
It seems like the fix did not work. I created a schedule a few days ago which was supposed to trigger only when nobody is home. I was perplexed to see it trigger every day when we were home. Found this issue and you are right - in the frontend everything looks fine, but in the scheduler.storage some time slots do not have any conditions. This is what my conditions look like in the GUI:
![image](https://user-images.githubusercontent.com/9319842/149036986-82416bee-3de9-4154-81c8-7d23ab6b2adc.png)

**Comment by hubikj** [comment] 2022-01-12 00:16
I just tried to edit the schedule by removing one condition, saving, re-adding condition, and saving. Now the same conditions are applied to all slots, so I think my schedule will work, but the bug in the scheduler card is still there somewhere.
