### ISSUE TITLE
The translation does not work

### ISSUE THREAD

**Issue by sacha01** [nielsfaber/scheduler-card#38] opened 2020-09-14 09:41 UTC
Hello, sorry for my English, I am French.
I installed your programmer, everything works for me except it's in English.
I don't understand why French is not displayed.
My HA interface is in French. Maybe I have something wrongly installed?
Thanks for your help

Thank you for your work

Sacha

**Comment by KTibow** [comment] 2020-09-14 13:34
Try reloading, and making sure it's plain french.

**Comment by nielsfaber** [comment] 2020-09-14 14:52
I think the problem is caused by the card.
Many users have addressed this issue.
Sadly all works fine in my own HA config, so it is difficult to find the problem.
I am hoping to fix it somewhere next week.

**Comment by sacha01** [comment] 2020-09-14 15:21
ok, no rush, it's just for information.
Even if when it works it will be better 
A +

**Comment by KTibow** [comment] 2020-09-14 15:53
See anything in logs (HA and browser console)?

**Comment by nielsfaber** [comment] 2020-09-15 15:57
Please update to [v1.2.8](https://github.com/nielsfaber/scheduler-card/releases/tag/v1.2.8).
After updating open the console log of your browser.
You should see a badge "Scheduler Card" with the version + language that you are using.
Please let me know if your language is 'fr' or otherwise.

**Comment by sacha01** [comment] 2020-09-15 19:19
it's for you
![2020-09-15_211829](https://user-images.githubusercontent.com/4747262/93254768-291c5100-f799-11ea-81eb-e535dbceabf6.png)

**Comment by nielsfaber** [comment] 2020-09-15 19:29
Woah, that clarify things a bit more.
On which version of HA are you?

**Comment by sacha01** [comment] 2020-09-15 19:35
![2020-09-15_213409](https://user-images.githubusercontent.com/4747262/93256206-4b16d300-f79b-11ea-8e5e-a5b88d894ec2.png)

**Comment by nielsfaber** [comment] 2020-09-15 19:38
OK, perfect.
I will ask the dev team of HA about this.
It appears to be a problem outside of my controls.

**Comment by sacha01** [comment] 2020-09-15 19:40
ok thank you and good luck for the further development.

**Comment by nielsfaber** [comment] 2020-09-15 19:57
Could you maybe try this link:
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_localstorage
It should tell us whether your browser may be part of the problem.
The link should simply output ‘Smith’ if your browser is OK.

**Comment by nielsfaber** [comment] 2020-09-16 07:20
never mind, I am working on a fix.
The people from HA helped me out.

**Comment by nielsfaber** [comment] 2020-09-19 08:50
The fix is included in v1.3.0. 
Please try and let me know if things are improved.
I have trouble reproducing your issueso I'm not 100% sure its solved now.

**Comment by nagyrobi** [comment] 2020-09-19 10:25
Does not load Hungarian language at all.

**Comment by nielsfaber** [comment] 2020-09-21 07:06
I am assuming it is fixed with the new update.
Please re-open if you still have troubles.

**Closed by nielsfaber** 2020-09-21 07:06 UTC
Labels: bug
