### ISSUE TITLE
delete after trigger

### ISSUE THREAD

**Issue by elyobelyob** [nielsfaber/scheduler-card#231] opened 2020-11-23 01:35 UTC
I have the occasional usage (e.g. changing tv channel for a specific program) where I would want the trigger to be deleted immediately after it is completed.

I'd imagine this could be another option?

Anyhow, I'd love to see this.

Many thanks.

**Comment by nielsfaber** [comment] 2020-11-23 13:09
duplicate of #161 
This will come at some point..

**Closed by nielsfaber** 2020-11-23 13:09 UTC
