### ISSUE TITLE
Temperature rounds ups 

### ISSUE THREAD

**Issue by menocode** [nielsfaber/scheduler-card#445] opened 2021-09-04 20:20 UTC
### Checklist

- [ ] I am running the latest version.

### Expected behavior
When I set the temperature to 24.5 I was the temperature to go on at 24.5 degrees 

### Actual behavior
It goes on at 25.0 degrees. In the schedule- the slider shows me 24.5 but when I click save - it saves at 25.0

### Steps to Reproduce
 I set the schedule for a time and temperature. I've used this on several schedules and several temps (25.5) and the outcome was the same. Using the regular card I have not problem changing the temperature to .5 degree increments.
I tried to find the YAML script to see the variable that the schedule uses  - but I just find these: 

```

"title": "Schedule",
                    "path": "Schedule",
                    "icon": "",
                    "badges": [],
                    "cards": [
                        {
                            "type": "custom:scheduler-card",
                            "title": "Scheduler",
                            "include": [
                                "binary_sensor",
                                "climate",
                                "cover",
                                "device_tracker",
                                "fan",
                                "input_number",
                                "light",
                                "media_player",
                                "person",
                                "scene",
                                "switch",
                                "vacuum"
                            ],
                            "display_options": {
                                "primary_info": [
                                    "<b>{name}<b>: {action}",
                                    "additional-tasks"
                                ],
                                "secondary_info": "relative-time",
                                "icon": "hass:action"
                            }

```

```

                "entity_id": "switch.schedule__turn_on_off_night_shabbat_chag",
                "config_entry_id": "540ed17c5fe952fce3d052cd10a7aeea",
                "device_id": "527d1b2310dd2cbb0dab5bd6a8d7c088",
                "area_id": null,
                "unique_id": "47b7f1",
                "platform": "scheduler",
                "name": null,
                "icon": null,
                "disabled_by": null,
                "capabilities": {},
                "supported_features": 0,
                "device_class": null,
                "unit_of_measurement": null,
                "original_name": "Schedule #47b7f1",
                "original_icon": "mdi:calendar-clock"
```

**Comment by mjsambol** [comment] 2021-09-05 11:23
Duplicate of #427, fixed in PR #433.

**Closed** 2021-09-05 11:24 UTC
Labels: bug
