### ISSUE TITLE
Weekdays reverts to daily

### ISSUE THREAD

**Issue by aeklo** [nielsfaber/scheduler-card#90] opened 2020-09-29 18:25 UTC
Selecting Days: Weekdays, reverts to Daily nevertheless. Tried som different entities, but still can't make it stick to weekdays.

**Comment by KTibow** [comment] 2020-09-29 18:41
Looks like it's not sending that it was a weekday. Websocket capture for weekdays:
```json
{
    "type": "call_service",
    "domain": "scheduler",
    "service": "add",
    "service_data":
    {
        "actions":
        [
            {
                "entity": "humidifier.humidifier",
                "service": "humidifier.set_humidity",
                "service_data":
                {
                    "humidity": "54"
                }
            }
        ],
        "entries":
        [
            {
                "actions":
                [
                    0
                ],
                "time": "12:00"
            }
        ]
    },
    "id": 64
}
```
For every day:
```json
{
    "type": "call_service",
    "domain": "scheduler",
    "service": "add",
    "service_data":
    {
        "actions":
        [
            {
                "entity": "humidifier.humidifier",
                "service": "humidifier.set_humidity",
                "service_data":
                {
                    "humidity": "54"
                }
            }
        ],
        "entries":
        [
            {
                "actions":
                [
                    0
                ],
                "time": "12:00"
            }
        ]
    },
    "id": 66
}
```

**Comment by nielsfaber** [comment] 2020-09-29 18:43
no days provided means: repeat every day.
So there is something wrong in the code that prepares the message to be sent.

**Comment by nielsfaber** [comment] 2020-09-29 19:56
I found what was causing this bug and fixed it.
Actually the weekdays setting is stored fine (don't know what @KTibow did), it is just displayed wrong.
It will be solved with the next release.

**Comment by nielsfaber** [comment] 2020-09-30 13:44
@aeklo  Please update to v1.6.0 and close the issue if the problem is fixed for you.

**Closed** 2020-09-30 20:47 UTC
Labels: bug
