### ISSUE TITLE
graphics problem

### ISSUE THREAD

**Issue by yuripace** [nielsfaber/scheduler-card#232] opened 2020-11-23 08:29 UTC
The component is very good and works well!
I only have a graphics problem: in the condition, the above/below symbol or text don't appear (https://imgur.com/a/ZLdq2Dc)

note that i have the same problem with chrome or firefox. Cleared cache of both browser.

Thanks!

**Comment by nielsfaber** [comment] 2020-11-23 08:48
I’m not happy with how it looks either.
I will change it, and give a text field where you can enter the value

**Comment by yuripace** [comment] 2020-11-23 09:03
the above/below symbol, is a traslation problem (HA?) or something else is missing?

**Comment by nielsfaber** [comment] 2020-11-23 09:08
This should be in text. Try to switch your HA language to english and refresh the page.
If then its OK, there is a translation missing in your language.

**Comment by yuripace** [comment] 2020-11-23 09:10
Tried, but it's missing also in English

**Comment by nielsfaber** [comment] 2020-12-23 15:11
This should be fixed with the recent changes to the conditions editor.
Please test if it is OK now, close the issue if the problem is gone.

**Comment by nielsfaber** [comment] 2020-12-29 07:51
Closing due to lack of response.
please re-open if there are still issues.

**Closed by nielsfaber** 2020-12-29 07:51 UTC
Labels: bug, in development
