### ISSUE TITLE
Period not showing  days on Hebrew  language 

### ISSUE THREAD

**Issue by moshiko2312** [nielsfaber/scheduler-card#640] opened 2022-12-15 18:52 UTC
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.9

### Component Version

3.2.13

### Bug description

Period not showing  days on Hebrew  language 

<img width="653" alt="image" src="https://user-images.githubusercontent.com/48163773/207942831-14079b98-d1d0-4e37-8568-22274c2d04e9.png">

### Steps to reproduce

I create a new task and when I try to commit dates there is simply no information
If I pass a lesson of English everything appears fine

**Comment by nielsfaber** [comment] 2022-12-15 19:50
This is strange, since the date picker is part of HA.

Could you try creating an input_datetime (only date) via HA?
YOu can do so under Configuration -> Devices -> Helpers -> Create helper button (bottom) -> Date
After creating it, you can click it to see the info:
![image](https://user-images.githubusercontent.com/16861605/207953290-560b4a80-6a27-4a1a-b42a-3108ce34f4b4.png)

Here you should have the same field for date input.
I would like to know if this one works OK for you.
If so, I can probably fix the issue, otherwise, you might need to create a bug report in HA.

**Comment by moshiko2312** [comment] 2022-12-15 19:57
hi i do 
<img width="466" alt="image" src="https://user-images.githubusercontent.com/48163773/207954853-7ee8d66d-8394-41a5-9933-8eb2bb239db7.png">

<img width="459" alt="image" src="https://user-images.githubusercontent.com/48163773/207954900-f62f7def-04e8-4213-acd5-bafe29e4ac88.png">

**Comment by moshiko2312** [comment] 2022-12-15 19:59
all language  begins  RTL ITS same 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/48163773/207955423-f2c5a8e5-4d3d-4bab-b5c8-e132b0654581.png">

**Comment by nielsfaber** [comment] 2022-12-15 20:10
So the problem is in HA itself.
I think it's best if you create a bug report for it there: https://github.com/home-assistant/frontend/issues.
I am unable to help you with this.

**Comment by moshiko2312** [comment] 2022-12-15 20:11
ok thanks

**Comment by nielsfaber** [comment] 2022-12-18 14:37
I'm closing this issue because it is related to HA, not scheduler card.
If you think there is still an issue which I can help with, please let me know.

**Closed by nielsfaber** 2022-12-18 14:37 UTC
Labels: bug
