### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by alnavasa** [nielsfaber/scheduler-card#348] opened 2021-03-18 19:13 UTC
I pues I might missed this in the documentation, I can't find it, 

The situation:
I can edit the program from my user,
I want another user who is not administrator to be able to edit the program, but I don't want to give them full administrator privilege.

**Comment by alnavasa** [comment] 2021-03-18 19:14
Could we add a 


```
users_allowed:
  - admin
  - Paul
  - James


```

**Comment by nielsfaber** [comment] 2021-03-18 19:45
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/282

**Closed by nielsfaber** 2021-03-18 19:45 UTC
