### ISSUE TITLE
Card broken after Home Assistant 2022.12 Update

### ISSUE THREAD

**Issue by Joebinator** [nielsfaber/scheduler-card#642] opened 2022-12-17 22:08 UTC
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v.2.3.9

### Bug description

After i updated Home Assistant to version 2022.12 my Scheduler Card is not working anymore.

### Steps to reproduce

Updatet Home Assistant to 2022.12

### Additional info

I am running Home Assistant in German but the Card shows this message in yellow:

Es konnte keine Verbindung mit der
Schedulerkomponente hergestellt werden. Es
muss als Integration installiert werden, bevor
diese Karte verwendet werden kann.

**Comment by nielsfaber** [comment] 2022-12-18 05:25
I'm also on HA 2022.12 and for me it works fine.
Please check the HA logs for any errors related to scheduler, in the Developer Tools you could check that the schedule entities are working OK (state should be on/off, not unavailable).
If this is all OK, it might be an issue with browser cache.

**Comment by Joebinator** [comment] 2022-12-18 10:57
I i go into Integrations -> Scheduler, i see all my schedules. They work like normal.


The Logs don't show anything usefull in that matter i guess

2022-12-18 11:53:17.654 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2022-12-18 11:53:27.714 INFO (MainThread) [homeassistant.setup] Setting up scheduler
2022-12-18 11:53:27.714 INFO (MainThread) [homeassistant.setup] Setup of domain scheduler took 0.0 seconds
2022-12-18 11:53:28.466 INFO (MainThread) [homeassistant.components.switch] Setting up switch.scheduler


I could try to reinstall the Integration, but i guess i will be loosing all me schedules, so i need to write them down before.

**Comment by nielsfaber** [comment] 2022-12-18 14:23
The schedules are stored in the `.storage` folder (subfolder of the folder which has the configuration.yaml) in a file `scheduler.storage`. You could always restore your schedules by copying this file.

I don't know what causes this issue (error suggest the card cannot communicate with the integration), perhaps clearing the browser cache (or trying from another browser/device) will help.

**Comment by Soyde** [comment] 2022-12-20 18:47
Same issue here, and I can confirm that clearing the browser cache (or trying from another browser/device) works!

Thanks @nielsfaber

**Comment by sk8er000** [comment] 2022-12-26 10:44
Same issue here but clearing the browser cache does not work, it show again if I reboot HA but after a while or if I call the service:
`service: homeassistant.reload_config_entry
data: {}
target:
  entity_id:
    - switch.schedule_name`

I always get: 
`Could not connect with the scheduler component. It needs to be installed as integration before this card can be used.`

**Comment by verrecs** [comment] 2023-01-28 16:57
I am now unable to access the detail of an existing schedule or to create a new one.
I can see the list of the creadted schedule / event to enable or disable them.

I precise that I display the card in a browser_mod popup.

I have zero info in the log :/

**Comment by Kilill** [comment] 2023-02-25 15:16
Similar issue, but it seems related to if the card is shown via browser_mod.popup.
I have several of these cards on a normal dashboard where they all work just fine. I also all the same
but they are shown as popups from a floorplan tap_action and shown via browser_mod.popup and here it is not possible to open the schedule by clicking the title / status line, the on/off button to the right works, and clicking the small blue flame to the left pops the history card.

The issue can be verified by creating a minimalist dashboard like so:
```
type: custom:button-card
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      content:
        type: vertical-stack
        cards:
          - type: custom:scheduler-card
            include:
              - climate.thermostat_dwnbath
```
clicking on the button will pop the scheduler card , but clicking on the title does nothing.

**Comment by jr-k** [comment] 2023-03-03 21:33
Same issue here @Kilill .... @nielsfaber  any idea ?

**Comment by nielsfaber** [comment] 2023-03-07 06:06
Scheduler card opens a popup dialog when clicking on the 'add' button or an existing schedule.
The opening of this popup is suppressed when the card is embedded in a browser_mod popup.
I tried this locally and could not find a way to make the popup show up.

At this point I don't know if there is anything I could change on the side of scheduler-card to address this issue, or the problem is with browser_mod. But they don't play well together.

**Comment by nielsfaber** [comment] 2023-03-22 20:20
@verrecs @Kilill @jr-k I found a way to make the popup show from within a browser mod popup. I will make a release soon to fix this issue.

**Comment by verrecs** [comment] 2023-03-22 20:43
Amazing! Can’t wait to test it!

Stéphane Verrecchia

**Comment by nielsfaber** [comment] 2023-03-25 06:19
v3.2.9 of the card is now released, this should solve the compatibility issues with browser-mod.
@verrecs Can you please test it and confirm it works for you? Then we can close this issue.

**Comment by verrecs** [comment] 2023-03-25 13:01
@nielsfaber everything is working again! Thanks a lot, you're amazing!

**Comment by Kilill** [comment] 2023-03-25 15:59
Works with Firefox , Brave, Chrome and even with (shudder) Edge 
had to clear the cache to get it work on Brave though...

So \o/ solved!

**Closed** 2023-03-25 17:04 UTC
Labels: bug, in development
