### ISSUE TITLE
Schedule Scheme - Color Coding

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [nielsfaber/scheduler-card#546] opened 2022-03-25 13:22 UTC
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Currently, when creating a scheduling scheme, you see something like this:

![image](https://user-images.githubusercontent.com/5262735/160128019-dc72fb48-fb24-488f-9756-039f589f7256.png)

However, that would look nicely done with a tad of color!

Red for heat, Blue for cool, etc.

### Additional info

/pulls out MSPaint

![image](https://user-images.githubusercontent.com/5262735/160128564-5f9e9b1d-50a8-4ddc-8667-ff182d88fcb0.png)

**Comment by nielsfaber** [comment] 2022-03-26 07:24
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/520

**Closed by nielsfaber** 2022-03-26 07:24 UTC
Labels: feature_request
