### ISSUE TITLE
Feature request: add media players

### ISSUE THREAD

**Issue by nagyrobi** [nielsfaber/scheduler-card#51] opened 2020-09-17 14:47 UTC
Add media players with the most basic functions:
- turn on
- turn off
- select source (this has to get the list of sources from the selected media player)
- play
- stop
- set volume
- mute / unmute
- next / prev

**Comment by nielsfaber** [comment] 2020-09-19 08:55
You can add the `media_player` domain if you want to control it with scheduler.
But i don't think it should be part of the standard configuration, since i think most users don't want to program schedules for media players.
See https://github.com/nielsfaber/scheduler-card#options on how to set-up your own domain.

**Comment by nagyrobi** [comment] 2020-09-19 09:09
A scheduler with a media player is useful if somebody wants to set up an alarm clock, so the speakers play a tune or a TTS message on time. Also very useful to set up a sleep timer, like stop playback or turn off after 30/60/90/120 minutes. 
Another usage scenario is to simulate that somebody's at home, like turn on the TV or music playback for 1 hour and then turn it off, maybe combined with the [random](https://github.com/nielsfaber/scheduler-card/issues/26) request.

These are use cases which are most useful if done through Lovelace, and your scheduler solution would fit perfectly.

**Comment by nielsfaber** [comment] 2020-09-19 09:18
> A scheduler with a media player is useful if somebody wants to set up an alarm clock, so the speakers play a tune or a TTS message on time. 

Playing a tune or TTS message will require the user to set up a specific action (with the right service_params) as well.
Generically speaking, you could only trigger one of the actions you mentioned before.
A possibility for an alarm clock would be to turn on a media player, (set it to a fixed volume), and set source to FM. But currently, it is not possible to program such a sequence of actions with the scheduler.

> Also very useful to set up a sleep timer, like stop playback or turn off after 30/60/90/120 minutes.

Such functionality is currently not in scope for the scheduler. It is intended for executing actions at certain time of the day, not X time after an event.

I think current functionality of the scheduler is too limited to really be useful for media players, but again, you can already configure it as you like.

**Comment by nielsfaber** [comment] 2020-09-28 15:31
Media player is added in v1.5.0. Actions `turn_on`, `turn_off` and `select_source` are available. 
I think other actions are very user dependent, you will have to add them yourself.
Please try it out and close the issue if the problem is solved for you.

**Closed** 2020-09-29 18:49 UTC
Labels: enhancement, in development
