### ISSUE TITLE
Schema with sunset/sunrise option

### ISSUE THREAD

**Issue by override80** [nielsfaber/scheduler-card#421] opened 2021-06-03 22:29 UTC
Hi @nielsfaber ,

Do you believe it could be possible or useful to add sunset/sunrise to schema? For example, if I wanted to turn a light on 1 hour after sunset and turn it off at 11pm without using 2 different schedules.

Cheers

**Comment by nielsfaber** [comment] 2021-06-12 05:52
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/289

**Closed by nielsfaber** 2021-06-12 05:52 UTC
