### ISSUE TITLE
Scheduler rounds temperatures

### ISSUE THREAD

**Issue by macieksonik** [nielsfaber/scheduler-card#439] opened 2021-08-31 20:24 UTC
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
I am trying to set climate (ESPHome thermostat) temperature exact but scheduler-card (in schema mode) rounds values to int. 

### Actual behavior
Setting 23.6 gives me 24. Setting 23.4 gives me 23. Earlier (haven’t use scheduler settings for some time) it was working OK. 

### Steps to Reproduce
Scheduler component v3.1.3
Scheduler-card v2.1.4
Core 2021.8.8

EDIT: downgrades to v3.1.2 and v2.1.3 eliminates the bug.

**Comment by lichen111** [comment] 2021-09-01 15:27
Same on my side

**Comment by mjsambol** [comment] 2021-09-02 20:35
This is fixed in PR #433 you can try cloning the repos and building locally.

**Comment by nielsfaber** [comment] 2021-09-03 06:37
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/427

**Closed by nielsfaber** 2021-09-03 06:37 UTC
Labels: bug
