### ISSUE TITLE
Week-end mode It didn't work

### ISSUE THREAD

**Issue by mycanaletto** [nielsfaber/scheduler-card#271] opened 2020-12-29 10:12 UTC
I have a workday: configured as follows :
- platform: workday
  country: FRA
  workdays: [mon, tue, wed, thu, fri, sat]
  excludes: [sun, holiday]

Monday to Saturday are working days.

Sunday and Holidays are therefore for the Scheduller days of the Weekend.

And today, Sunday, no actions planned to take place over the Week-End have been launched…

Either I didn’t understand anything about workday: configuration, or the scheduler has a problem.

**Comment by nielsfaber** [comment] 2020-12-29 10:28
> Sunday and Holidays are therefore for the Scheduller days of the Weekend.

This is indeed how it should work, so something seems to be wrong.
I will check it out.

**Comment by mycanaletto** [comment] 2020-12-29 10:38
For the moment I haven't changed anything to see what will happen on 01/01.

**Comment by nielsfaber** [comment] 2020-12-29 12:49
I just checked but I am unable to reproduce this problem.

I created this schedule:
![image](https://user-images.githubusercontent.com/16861605/103284346-4937ef00-49db-11eb-8954-233ec3c53c44.png)

I configured the workday sensor to exclude tuesday (today):
![image](https://user-images.githubusercontent.com/16861605/103284514-b481c100-49db-11eb-9de3-2a3ea2b217ae.png)

The result:
![image](https://user-images.githubusercontent.com/16861605/103284582-e561f600-49db-11eb-9805-6037ec9f34f8.png)

Or without the card:
![image](https://user-images.githubusercontent.com/16861605/103284615-fa3e8980-49db-11eb-824f-17bdbed86b35.png)


Likewise, if I change the workday sensor to include tuesdays in workdays:
![image](https://user-images.githubusercontent.com/16861605/103284710-425dac00-49dc-11eb-8dfa-7e335a5e3d92.png)

The result becomes:

![image](https://user-images.githubusercontent.com/16861605/103284682-2954fb00-49dc-11eb-9e27-9d34d531712a.png)


So, from what I can see:

> the scheduler has a problem.

This doesn't seem to be the case.

Can you create some test and share screenshots to illustrate the problem you have?

**Comment by nielsfaber** [comment] 2020-12-29 12:53
For completeness, adding a test for holiday case:
```
binary_sensor:
  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - "2020-12-29"
```

Today = 2020-12-29 = holiday, so I would expect the schedule to be skipped (although tuesday is a workday).

Result:
![image](https://user-images.githubusercontent.com/16861605/103284988-20b0f480-49dd-11eb-9422-a24f59137ff3.png)

Which is as I would expect.

**Comment by mycanaletto** [comment] 2020-12-29 13:02
This schedule is planed for wee-ends
![image](https://user-images.githubusercontent.com/45459269/103285237-db40f700-49dd-11eb-8d5e-211b9804eb45.png)

And the next occurence is indicated for Sunday (Dimanche) while 01/01 (Friday) is a holiday.
![image](https://user-images.githubusercontent.com/45459269/103285201-bcdafb80-49dd-11eb-89bf-b28584d167b9.png)

But last Sunday the planned actions did not take place.

The workday setting: (I checked it is off on Sunday)

`- platform: workday
  country: FRA
  workdays: [mon, tue, wed, thu, fri, sat]
  excludes: [sun, holiday]`

**Comment by nielsfaber** [comment] 2020-12-29 13:45
> And the next occurence is indicated for Sunday (Dimanche) while 01/01 (Friday) is a holiday.

The occurence will be rescheduled on the day itself (at 00:00 the workday sensor updates).
This is because the workday sensor does not expose the list of holidays that you configured, it is only visible with the ON/OFF state.

> But last Sunday the planned actions did not take place.

If this happens again, then let me know, and try to make screenshots.

**Comment by mycanaletto** [comment] 2021-01-01 02:21
I voluntarily put a slot that starts at midnight on weekends and holidays at 19.5° when it is normally at 19° during the week in order to see what would be taken into account on the night of 01/01 (holiday).

And alas it is the schedule of the week which was triggered at 19°, which means that the holiday is not taken into account, just as it was not taken into account last Sunday.

Next step on Sunday.

A very beautiful year 2021 !

**Comment by nielsfaber** [comment] 2021-01-01 17:34
Please take some screenshots to show what goes wrong.
I cannot help you otherwise (since in my test it worked as I expected).
Please share the following:
* History data of the workday sensor (to verify it is OFF when it is a holiday/weekend)
* Configuration of the schedule entity (could be screenshot from the Developer Tools -> Entities page)
* History data of the schedule entity (to show that it indeed went to triggered state when it should not)

**Comment by mycanaletto** [comment] 2021-01-01 17:44
![image](https://user-images.githubusercontent.com/45459269/103443512-4f8acd00-4c60-11eb-889e-1aa12b04d5f2.png)
```entries:
  - 67DT0000T0900A0C01
  - 67DT0900T2359A1C01
actions:
  - service: set_temperature
    entity: climate.thermostat_sejour
    hvac_mode: heat
    temperature: 19.5
  - service: set_temperature
    entity: climate.thermostat_sejour
    hvac_mode: heat
    temperature: 21
conditions:
  - entity: input_boolean.thermostats_away
    match_type: is
    state: 'off'
  - entity: input_boolean.thermostats_on_off
    match_type: is
    state: 'on'
next_trigger: '2021-01-03T00:00:00+01:00'
friendly_name: 'TH Séjour : Dimanche et Férié'
icon: 'mdi:calendar-clock'```


The one that had to be triggered
![image](https://user-images.githubusercontent.com/45459269/103443608-52d28880-4c61-11eb-9f0d-0b6c3f1921eb.png)


The one that was triggered (week)
![image](https://user-images.githubusercontent.com/45459269/103443604-43533f80-4c61-11eb-8ad4-1e4515a4a13a.png)

**Comment by mycanaletto** [comment] 2021-01-01 17:44
![image](https://user-images.githubusercontent.com/45459269/103443614-5e25b400-4c61-11eb-9b82-f2775ea6db15.png)

**Comment by mycanaletto** [comment] 2021-01-01 17:44
![image](https://user-images.githubusercontent.com/45459269/103443623-6e3d9380-4c61-11eb-8eae-2eabbb051fbb.png)

**Comment by mycanaletto** [comment] 2021-01-01 17:46
![image](https://user-images.githubusercontent.com/45459269/103443637-a04ef580-4c61-11eb-8c2a-c2309af33e58.png)

**Comment by nielsfaber** [comment] 2021-01-01 17:47
The screenshots are from the old version of the scheduler-component.
Please update before..

**Comment by mycanaletto** [comment] 2021-01-01 17:50
OK, it's not my home and I'm not going to have to do it remotely and risk losing all these configurations?

This answer reminds me of Microsoft's support, but I'm going to do it...

Have you changed anything in the meantime?

**Comment by nielsfaber** [comment] 2021-01-01 17:58
> This answer reminds me of Microsoft's support, but I'm going t:o do it...

I take that as a compliment, since Microsoft is a big professional organisation 😄 

> Have you changed anything in the meantime?

I add notes to each release, probably many changes yes..
That's also why I would like you update first, maybe the problem is already solved in the meantime (though I don't remember changing anything about this recently).

**Comment by mycanaletto** [comment] 2021-01-01 18:00
I'm in the process of doing it, I hope I don't have to do it all over again because my brother might not have any heating...

**Comment by nielsfaber** [comment] 2021-01-01 18:02
I recommend to take screenshots or notes of the current schedules.
Many people have reported problems of upgrading to the new version.
If the functionality is critical, maybe better to save it for a moment where it is not a problem..

**Comment by mycanaletto** [comment] 2021-01-01 18:09
It's OK, after the two restarts I got the schedules back (bravo, I was afraid to spend hours redoing everything with the screenshots). I programmed a test in 15 minutes we'll see...

**Comment by nielsfaber** [comment] 2021-01-01 18:19
OK good!
The schedules are now stored in .storage/scheduler.storage so there is no risk of losing them again (unless the file goes corrupt or you remove the integration).
With the new version the schedules have an attribute "weekdays".
If a schedule has value "workday" or "weekend" it should be working with the workday integration.

**Comment by mycanaletto** [comment] 2021-01-01 18:19
Yes !!!!

So you had corrected that, but I'm reading the release notes and I hadn't seen anything.

The schedule of 19.15 weekend went well today 01/01 and the following ones are well programmed for.

![image](https://user-images.githubusercontent.com/45459269/103444166-3dac2880-4c66-11eb-8c74-74f9e55dac6c.png)

Bravo et merci !

**Comment by nielsfaber** [comment] 2021-01-01 18:25
I'm glad to hear it worked!
The new v3.0.0 release of the component had many structural changes, maybe I solved a bug without knowing it. 
It also depends on which version you were running before updating.

If you experience problems again please let me know and I will help investigate.
I am not using the workday integration myself, and I get very few questions about it, so your feedback is very welcome.
Please close the issue if you all is OK now.

**Comment by mycanaletto** [comment] 2021-01-01 18:28
I was using the last update 2.x before 3.0

If I understood correctly the Workday conditions are re-evaluated every day at 00:00 and the other conditions before each schedule start?

**Comment by nielsfaber** [comment] 2021-01-01 19:00
As you can see here:

![](https://user-images.githubusercontent.com/45459269/103443512-4f8acd00-4c60-11eb-889e-1aa12b04d5f2.png)

The workday sensor exposes the list of days that are configured as workdays.

Scheduler will read from that list for which days it needs to repeat, so it will normally not be rescheduled at 00:00.

The rescheduling only occurs for holidays.
The workday sensor is updated every day at 00:00, and the scheduler watches these updates.
In case that today is a holiday, the workday sensor will be OFF at 00:00, no matter what weekday it is.

**Comment by mycanaletto** [comment] 2021-01-01 19:15
Cool 

Thank you for your help. Now I have to continue my article, I didn't want to do it until this particular problem was solved ;-)

**Closed** 2021-01-01 19:15 UTC
Labels: bug
