### ISSUE TITLE
Friday 30.4.2021 is not working day

### ISSUE THREAD

**Issue by panenka** [nielsfaber/scheduler-card#372] opened 2021-04-29 15:39 UTC
Current version has bug. For example, Friday 30.4.2021 is not working days and scheduled actions are not not tomorrow but at Monday 3.5.2021.

**Comment by nielsfaber** [comment] 2021-04-29 15:59
Duplicate of https://github.com/nielsfaber/scheduler-component/issues/86
Actually this should be solved by updating scheduler-component to the newest version.

**Closed by nielsfaber** 2021-04-29 15:59 UTC

**Comment by panenka** [comment] 2021-04-29 16:27
I have been updated this component a few minutes before I have been found this bug. There is no newer version now.
