### ISSUE TITLE
Input target temperature when Auto climate

### ISSUE THREAD

**Issue by erikmex-root** [nielsfaber/scheduler-card#678] opened 2023-02-18 10:16 UTC
### Checklist
- [ x] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
It seems to be missing the target temperature when switching climate to auto. By default It takes the last temperature sent to the device regardless of it was heating or cooling. The use case is to set a specific auto temperature at different times of the day and week. 

### Additional info
[some example of how the new functionality should look like]
Adding one more temperature slide control when switching to auto.

**Comment by alpharesearch** [comment] 2023-02-19 16:23
I have an issue that is related to auto mode as well. I'm not sure why it's now called Heat/Cool, but I believe it was auto in the past. This thermostat come into HA via ST. In ST the value is still auto. Anyway,  my guess would be that the / character can not be displayed in the Scheduler-card correctly. So I think the whole auto mode or heat/cool mode needs to be looked at.

![Screenshot_20230219_110712_Home Assistant](https://user-images.githubusercontent.com/317055/219960217-ee07f33b-6392-4fc8-9e50-ada0433245ce.jpg)
![Screenshot_20230219_110735_Home Assistant](https://user-images.githubusercontent.com/317055/219960252-2f7a563e-968b-475c-9835-c40767b19bd4.jpg)

**Comment by sven337** [comment] 2023-03-08 09:35
> As far as I know, the ‘auto’ mode is reserved for cases where the climate device controls the setpoint. For example if it is following an internally stored time schedule. In case you want to have a climate device follow a setpoint, the mode ‘heat’ (or ‘cool’) is appropriate. Am I missing something?

At least my device allows setting the temperature, so it's unfortunate not to have it available in "auto".
As for "heat", it's not usable in my case due to https://github.com/Koenkk/zigbee2mqtt/issues/16961, a work around is to use "auto". It would be very helpful to have the temperature slider in that case :) 

Thanks

**Comment by alpharesearch** [comment] 2023-03-08 13:04
Auto mode in my z wave thermostat only automatically switches between heating and cooling, but both setpoint are manually set. If the temperature drops under the heat setpoint the heating kicks in, if the temperature gets above the cool setpoint the cooling starts. This mode is good for early spring when temperatures are all over the place.

**Comment by nielsfaber** [comment] 2023-03-08 13:08
FYI: I'm working on adding an optional parameter for the temperature setting when setting the mode to auto.
It will look like this:
![image](https://user-images.githubusercontent.com/16861605/223721067-060ee05b-7918-4a61-9419-edc7f33c8588.png)

The checkmark can be left unchecked to only switch the mode, without setting a temperature.
I think this is a best-of-both-worlds solution.

**Comment by nielsfaber** [comment] 2023-03-08 16:59
This is now added in the v3.2.8 release.
@erikmex-root Please update the card version and test it locally.
You can close the issue if the problem is solved, otherwise please let me know.

**Comment by erikmex-root** [comment] 2023-03-08 19:35
Thanks Niels, It works like a charm!

**Closed** 2023-03-08 19:36 UTC
Labels: in development, feature_request

**Comment by sven337** [comment] 2023-03-08 20:17
The temperature checkbox/slider does not seem to appear for me:
![screenshot_2023-03-08_21-17-14](https://user-images.githubusercontent.com/6923298/223840229-b4a1615a-ac69-4e84-bbc7-a0d2933e63df.jpg)

**Comment by erikmex-root** [comment] 2023-03-08 20:26
I went to v3.2.7 then back to v3.2.8 to force the reinstallation     And the temperature slide control was there for auto mode. Try that, I hope it works for you. /Erik
