### ISSUE TITLE
I can't enable/disable ths scheduler with a button

### ISSUE THREAD

**Issue by anarro** [nielsfaber/scheduler-card#54] opened 2020-09-21 06:13 UTC
Hi @nielsfaber 

With the latest version 1.3.2 we cannot change the state (enable / disable) from the user interface button, I try to update the cache but nothing ... clicking it opens in edit mode.

![image](https://user-images.githubusercontent.com/8436433/93736870-f4b5f400-fbe1-11ea-9003-6fa3a8cd295b.png)

Thank you,
Antoni.

**Comment by nielsfaber** [comment] 2020-09-21 06:25
Ah you’re right!
If you click the switch you go directly to the editor.
Must be caused by the new color effect.
Sorry for the troubles 😅

**Comment by nielsfaber** [comment] 2020-09-21 07:04
Thanks for reporting, it is fixed with [release v1.3.3](https://github.com/nielsfaber/scheduler-card/releases/tag/v1.3.3)

**Closed by nielsfaber** 2020-09-21 07:04 UTC
