### ISSUE TITLE
Show resize handlers and tooltips only for selected slot + add "smart" tooltips

### ISSUE THREAD

**Issue by Misiu** [nielsfaber/scheduler-card#225] opened 2020-11-17 14:01 UTC
Currently, the timeline view is displaying all the timeslots, all tooltips, and all drag handlers (round buttons with arrows).
If we have more timeslots the tooltips overlap:
![image](https://user-images.githubusercontent.com/1741838/99397740-bd16b000-28e3-11eb-8f03-27202e36f620.png)

My idea is to initially display the timeline without the tooltips and without the drag handlers, but with vertical lines as separators:
![image](https://user-images.githubusercontent.com/1741838/99398864-32cf4b80-28e5-11eb-8be8-78c575b4198d.png)

 then when you click (or press) on the slot you will see the tooltips and the drag handlers, but only for the currently selected slot:

![image](https://user-images.githubusercontent.com/1741838/99399270-b7ba6500-28e5-11eb-982d-361b3c51340f.png)

Also, please add "smart" tooltips. Idea is to have tooltips default as it, but they should move to the left or right to not overlap each other.
With multiple tooltips, this won't help, but with two this will make a difference.

**Comment by nielsfaber** [comment] 2020-11-17 17:04
My issue label bot is broken 😢 
Obviously this is a feature request.

I like the idea and will try to add this in a next release.

I'm wondering about when to show tooltip in case you're dragging with markers.
Ofcourse you want to see the tooltip of the marker you are moving, but maybe also its left + right neighbour..
The problem is that you can still get the collisions if so.

Dragging markers is not related to having slot selected.
You can even select a timeslot, and then drag a marker that is not related.

**Comment by Misiu** [comment] 2020-11-17 17:25
I think the tooltips should be visible as soon as you select a slot and stay visible untill you select other slot (they should be visible during drag)
About showing the neighbour's, not sure about that, this will cause tooltips collisions.
My idea behind hiding by default tooltips and drag markers was to have a clear view when you go to that view and only show what you need and when you need it.

**Comment by KTibow** [comment] 2020-11-18 01:29
@nielsfaber odd that it's broken. Can you check here: https://github.com/marketplace/issue-label-bot And see if there's a problem? Also check your repo in the [website](https://label-bot-prod.mlbot.net/).

**Comment by nielsfaber** [comment] 2020-11-18 05:32
@KTibow mlbot.net is throwing me an error:
```
Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds. 
```
I told you stuff always breaks for me 😄

**Comment by KTibow** [comment] 2020-11-18 15:20
Well hopefully it gets back up soon. There's also another one that looks for keywords instead of using ML.

**Comment by nielsfaber** [comment] 2020-11-18 15:21
The website seems to be back already. Just very slow still...

**Comment by nielsfaber** [comment] 2020-11-18 15:29
@Misiu  I released v1.9.7 which contains your proposed improvements.
Usually I am not very conformistic, but the changes are almost literally as you proposed.

There is still a limitation to the minimum size of timeslots that you can reach, due to the drag handlers. I gave them a bit extra space (like mwc-icon-button) because on mobile phones it is difficult to touch the button exactly.

I'm not really happy with the fact that the tooltips can now go past the extends of the card (if you go all the way to 00:00 or 23:59).
But since there is no easy way to get around this, I decided to release as-is.

Think the update improves some aspects, but certainly not all. Let me know what you guys think.

**Comment by acseven** [comment] 2020-11-18 16:02
If I may, the changes are great overall, but there's now an added difficulty to select very short time periods (see number 2 in the screenshot below). Maybe with some arrows to cycle though time periods without direct selection?

![image](https://user-images.githubusercontent.com/1176371/99554660-595db700-29b7-11eb-8ed2-8eea9e2e9993.png)

**Comment by nielsfaber** [comment] 2020-11-18 16:09
@acseven If I may ask, why did you need a timeslot of like 1 minute?
Personally I don't use scheduler for super-time-critical jobs. I am always curious why users want the precise resolution.
My suggestion would be to keep time slots at 1 hour or longer.
But I don't know how big of a limitation this would be to some people.. I would like to hear your use-case.

**Comment by acseven** [comment] 2020-11-18 16:13
No worries. Users always find the weirdest stuff to do! :) The timeslot is actually 10 minutes. The idea here is to open windows shutters at a specific level to let some light in at first and 10 minutes later open it in full. 
Your scheduler is awesome for this!

**Comment by nielsfaber** [comment] 2020-11-23 08:55
@Misiu can we close this? Or you're not satisfied with the improvements yet?

**Comment by Misiu** [comment] 2020-11-23 09:22
@nielsfaber I'm very satisfied! Please give me a day or two to give this a try. I'd like to test a couple of scenarios.

**Comment by Misiu** [comment] 2020-11-24 21:41
@nielsfaber I've just set up a new test environment and everything looks and work perfect :)
I'll test this even more. If I find something I'll report it as new issues.

Thanks!

**Closed** 2020-11-24 21:42 UTC
Labels: enhancement

**Comment by acseven** [comment] 2020-11-28 15:52
Hi, sorry for bumping this, but the slider does have some glitches has seen in the video below:

![image](https://user-images.githubusercontent.com/1176371/100519735-c03a5780-3191-11eb-826c-3c0bc0392fa5.gif)
