### ISSUE TITLE
Can't interact with Scheduler Card while inside of browser-mod popup

### ISSUE THREAD

**Issue by Anon666333** [nielsfaber/scheduler-card#685] opened 2023-03-09 19:39 UTC
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.7

### Component Version

3.2.14

### Bug description

using the card is fine on lovelace directly (love it, thank you!), however, I'm trying to nest it inside of a pop-up card (via browser-mod) and as soon as it's inside of the popup, all tap functions cease to work.
Now, I could just be missing something stupidly obvious, but with other entities that fall inside of a pop-up card, I don't need to necessarily define the tap_action as if it is undefined, the default will apply. Please let me know if you think I'm doing something wrong, if there this is causing conflicts with the custom card.
Please note, this popup action is inside of a mushroom-template-chip, if that makes a difference (I don't believe it should).

```  
- type: template
    icon: mdi:calendar-edit
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Schedules
          content:
            type: grid
            columns: 1
            square: false
            cards:
              - type: custom:mod-card
                card_mod:
                  style: |
                    ha-card {
                      background: radial-gradient(rgb(0,0,0, 80%) 25%, rgb(0,0,0, 0%));
                      font-weight: bold !important;
                      text-align: center;
                      border: none;
                    }
                card:
                  square: false
                  columns: 1
                  type: grid
                  cards:
                    - type: custom:scheduler-card
                      include:
                        - input_boolean.kill_switch_jps_room_motion
                        - input_boolean.kill_switch_master_bedroom_motion
                        - input_datetime.front_lights_off_time
                        - input_datetime.front_lights_on_time
                      exclude: []
                      title: false
                      sort_by:
                        - state
                        - title
                      display_options:
                        primary_info: '{entity}: {action}'
                        secondary_info:
                          - relative-time
                      customize:
                        input_boolean.kill_switch_master_bedroom_motion:
                          name: Master Bedroom
                          icon: hass:motion-sensor
                          actions:
                            - service: turn_on
                              name: Disable Motion
                              icon: hass:motion-sensor-off
                            - service: turn_off
                              name: Enable Motion
                              icon: hass:motion-sensor
                        input_boolean.kill_switch_jps_room_motion:
                          name: JPs Bedroom
                          icon: hass:motion-sensor
                          actions:
                            - service: turn_on
                              name: Disable Motion
                              icon: hass:motion-sensor-off
                            - service: turn_off
                              name: Enable Motion
                              icon: hass:motion-sensor
                      discover_existing: true
                      card_mod:
                        style: |
                          ha-card {
                            background: radial-gradient(rgb(0,0,0, 80%) 25%, rgb(0,0,0, 0%));
                            border: none;
                          }
```

### Steps to reproduce

Added the scheduler card inside of a popup box from browser mod, and tap actions on the scheduler card ceased working.
code is attached above, but I'm going to include it here as well (sorry for the duplication)

```
- type: template
    icon: mdi:calendar-edit
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          title: Schedules
          content:
            type: grid
            columns: 1
            square: false
            cards:
              - type: custom:mod-card
                card_mod:
                  style: |
                    ha-card {
                      background: radial-gradient(rgb(0,0,0, 80%) 25%, rgb(0,0,0, 0%));
                      font-weight: bold !important;
                      text-align: center;
                      border: none;
                    }
                card:
                  square: false
                  columns: 1
                  type: grid
                  cards:
                    - type: custom:scheduler-card
                      include:
                        - input_boolean.kill_switch_jps_room_motion
                        - input_boolean.kill_switch_master_bedroom_motion
                        - input_datetime.front_lights_off_time
                        - input_datetime.front_lights_on_time
                      exclude: []
                      title: false
                      sort_by:
                        - state
                        - title
                      display_options:
                        primary_info: '{entity}: {action}'
                        secondary_info:
                          - relative-time
                      customize:
                        input_boolean.kill_switch_master_bedroom_motion:
                          name: Master Bedroom
                          icon: hass:motion-sensor
                          actions:
                            - service: turn_on
                              name: Disable Motion
                              icon: hass:motion-sensor-off
                            - service: turn_off
                              name: Enable Motion
                              icon: hass:motion-sensor
                        input_boolean.kill_switch_jps_room_motion:
                          name: JPs Bedroom
                          icon: hass:motion-sensor
                          actions:
                            - service: turn_on
                              name: Disable Motion
                              icon: hass:motion-sensor-off
                            - service: turn_off
                              name: Enable Motion
                              icon: hass:motion-sensor
                      discover_existing: true
                      card_mod:
                        style: |
                          ha-card {
                            background: radial-gradient(rgb(0,0,0, 80%) 25%, rgb(0,0,0, 0%));
                            border: none;
                          }
```

**Comment by S1M8N** [comment] 2023-03-19 20:56
Yes me too, it's problematic in my dashboard...

**Comment by sliann** [comment] 2023-03-20 21:05
Same problem here

**Comment by nielsfaber** [comment] 2023-03-21 19:17
As also discussed in #642, when placing scheduler card inside a browser-mod popup, the editor dialog is no longer showing up. 
This is an incompatibility issue between scheduler card and browser-mod.
At this point I don't know how to address the issue, I don't even _if_ it can even be solved from the side of scheduler-card.

I installed browser-mod locally to reproduce this issue. 
The action which opens a dialog is simply suppressed within the browser-mod popup. The content of the dialog does not matter.
Hence I would say that _any_ card placed inside a browser-mod popup would show the same issue and be incapable of opening another dialog window.
On the contrary, I noticed that the 'more info' dialogs of individual entities can still be accessed within browser-mod popup. 
I would like to solve the problem, but as said, I don't have any clues on how to do so at this moment.

**Comment by Anon666333** [comment] 2023-03-22 21:20
> I have to correct my previous statement:
> 
> > At this point I don't know how to address the issue, I don't even if it can even be solved from the side of scheduler-card.
> 
> Today I managed to make a dialog show up within a browser-mod ppup in some code experiment. I will adapt the code for scheduler to make it compatible and create a release later this week for it.

@nielsfaber you rock! Thank you so much for taking the time to sort this out! Can't wait for the update. It's going to really help to clean up the dashboard. Sticking it inside a swipe card was my next-best-option, but I really want it in the template chip and to open with a popup.

**Comment by nielsfaber** [comment] 2023-03-25 06:20
v3.2.9 of the card is now released, this should solve the compatibility issues with browser-mod.
@Anon666333 Can you please test the updated version?
If the problems are solved now, you can close the issue. Otherwise let me know.

**Comment by Anon666333** [comment] 2023-03-25 11:24
> v3.2.9 of the card is now released, this should solve the compatibility issues with browser-mod.
> @Anon666333 Can you please test the updated version?
> If the problems are solved now, you can close the issue. Otherwise let me know.

Awesome! I'm going to give it a test this morning and let you know how it goes.
Again, really appreciate you diving into this.

**Comment by Anon666333** [comment] 2023-03-25 11:45
> v3.2.9 of the card is now released, this should solve the compatibility issues with browser-mod.
> @Anon666333 Can you please test the updated version?
> If the problems are solved now, you can close the issue. Otherwise let me know.

It works!!! Thank you so much.

**Closed** 2023-03-25 11:45 UTC
Labels: bug, in development

**Comment by ghostist** [comment] 2023-03-26 15:59
Goooooood job!
I've noticed this issue recently, since I use floorplan and rely heavily on browser-mod popup. So I jumped to a separate page to use scheduler-card. Now I don't have to!
Thanks again!
