### ISSUE TITLE
Disabling one scheduler disable an other one

### ISSUE THREAD

**Issue by JSteunou** [nielsfaber/scheduler-card#204] opened 2020-11-06 12:09 UTC
Issue with the list of scheduler: when disabling one scheduler, the list get sorted and another scheduler get disabled too.

This generally happens in front-end dev because list are keyed by index instead of by unique id. After resorting the list, the new component getting the same  index than the previous one is updated the same way.

![Capture vidéo 2020-11-06 08 51 02](https://user-images.githubusercontent.com/2323127/98364557-48b15680-2031-11eb-9665-5e1609b83201.gif)

**Comment by elyobelyob** [comment] 2020-11-06 21:13
Same issue. It seems to disable the last on the list, then the next, then the next when repeated. However, re-enabling the lowest disabled, also re-enables the last disabled .. which you can see on the over gif.

**Comment by KTibow** [comment] 2020-11-07 01:21
@nielsfaber did you see this? Any ideas on what's causing this?

**Comment by JSteunou** [comment] 2020-11-07 10:52
I'm more a React the lit-html / polymer guy so my 1st reaction was to check about keyed list item, classic bug using React list with reorder. But lit-html does not seem to have this concept. I found this interesting part https://lit-html.polymer-project.org/guide/writing-templates#repeating-templates-with-the-repeat-directive that could help, but to improve performance.

The issue must be elsewhere. @nielsfaber if you have some time this week-end to show me how you dev & debug inside HA I could help you with the front-end.

I am a stranger to dev in HA but not to JS / TS / React web app

**Comment by nielsfaber** [comment] 2020-11-07 11:56
The problem is just that the list re-sorts when you disable one item.
And then the click event is also fired on the switch that appears under your mouse.

I implemented some blocking mechanism to prevent the list from resorting when disabling an item, but it is a bit hacky.
Apparently it works 9/10 times.. You're the first one to notice this.

**Comment by elyobelyob** [comment] 2020-11-07 13:03
Here's what's happening on mine.
![scheduler_card](https://user-images.githubusercontent.com/298022/98441923-64802f80-20f9-11eb-9d23-9882333fe0a5.gif)

I also notice that the bottom for are not actually re-enabled (they are greyed out in the gif). When I visit a different browser, I get them disabled ... 

<img width="497" alt="Screenshot 2020-11-07 at 13 01 07" src="https://user-images.githubusercontent.com/298022/98441950-92fe0a80-20f9-11eb-9582-2d1120884436.png">

**Comment by nielsfaber** [comment] 2020-11-11 16:01
I could reproduce this scenario as well.
Made some changes to improve this.

List should not be re-sorted when you toggle the switches.

Release will follow soon!

**Comment by nielsfaber** [comment] 2020-11-13 09:07
Please try updating to v.1.9.5. It should fix this behaviour.

**Comment by elyobelyob** [comment] 2020-11-13 14:06
Hi, the updates have fixed all the issues I raised. Many thanks.

I have one question, as to whether after disabling a switch and refreshing, should the switch locate itself at the bottom? It doesn't do it immediately (i.e. requires a refresh) and it's no longer time based in the list. 

This may be intended, but perhaps not.

<img width="490" alt="Screenshot 2020-11-13 at 13 41 16" src="https://user-images.githubusercontent.com/298022/99078973-2aaa9f80-25b7-11eb-9f95-c73f006d0c45.png">

For me, it makes sense to remain in place to show when it is supposed to action whether switched on or not?

<img width="490" alt="Screenshot 2020-11-13 at 13 41 16b" src="https://user-images.githubusercontent.com/298022/99079887-701b9c80-25b8-11eb-8374-4f887bd642a1.png">

It's just a visual thing for me, but the switch is the clue as to whether it's engaged or not. It's quick and easy to see if it remains in its actual trigger position.

Sorry if I'm nit-picking!

**Comment by nielsfaber** [comment] 2020-11-14 15:20
@elyobelyob 
This is the current behaviour, (all of which is intentionally done):
1. The list of schedules is sorted chronologically based on the time to next trigger.
2. Disabled items are not sorted, they are placed at the bottom of the list.
3. When disabling/enabling schedules, the re-sorting is prevented.
It is very confusing and counter-intuitive to have the list re-sorting, since the toggle switch under your mouse will be replaced with another.
4. Refreshing the page causes 1+2 to be triggered, so the list order may be changed.


If I understand you correctly, you don't like point 2.
I think this is a matter of taste.

Everyone has different reasons for disabling schedules.
Some users like to only activate schedules when on holidays etc.
In that case they don't want to see them most of the time, so I guess it would be preferable to have them all together in the bottom.

I'm OK with (neutral about) changing the behaviour, but maybe it would result into protest of some users.
I invite you to open a poll/vote in the HA discussion thread about your proposal.
If most users like your suggestion then I'll update it.
Maybe there are even other possibilities (such as grouping as I have done for discovered/excluded schedules).

**Comment by elyobelyob** [comment] 2020-11-14 15:49
Thanks, I suspected it might be intentional. Would it be possible to add the option in settings whether to have it re-order when disabled, keeping the default as it is now?

**Comment by nielsfaber** [comment] 2020-11-16 10:57
> Thanks, I suspected it might be intentional. Would it be possible to add the option in settings whether to have it re-order when disabled, keeping the default as it is now?

I checked, but the change is not very trivial. Requires changes in the scheduler_component as well. Because the sorting is based on the `next_trigger` property of the schedules, which is (currently) only exposed if a schedule is active/waiting.

I would only make this change if it is worthwhile, in the sense that multiple (/a majority of) users vote in favor of it.
Not sure if this should be a configurable property, this would emphasize that not everyone has benefit from the improvement. I prefer to keep configuration at a minimum (it complicates the card).

If you are still strongly in favor of this change, please create a separate FR for it. 
I'm closing this issue because we're getting off-topic.

**Closed by nielsfaber** 2020-11-16 10:57 UTC
Labels: in development
