### ISSUE TITLE
Something went wrong! Message format incorrect: length of value must be at least 1 for dictionary value @ data['timeslots']  Response error: 400

### ISSUE THREAD

**Issue by NickInManchester** [nielsfaber/scheduler-card#441] opened 2021-09-02 10:31 UTC
### Checklist
- [ Y] I checked for similar existing issues (both open and closed) before posting.
- [Y ] I am running the latest version.

### Expected behavior
[What you expected to happen]

Have a schedule to turn on/off a set of individual lights. Tried to remove one light from the schedule using the Card. Save the change and exit.
### Actual behavior
[What actually happened]

On trying to save the single change deselecting just one of the lights the error message in the report title pops up.

Browser console contains:

extension-api-normalizer.js:108 debug
8:1 Unchecked runtime.lastError: The message port closed before a response was received.
app.4e133b2d.js:5232 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
55704 @ app.4e133b2d.js:5232
extension-api-normalizer.js:108 debug
DomainAgeContentHandler.ts:19 domain 1.60
extension-api-normalizer.js:108 debug
password-vault-field-checker.js:51 Couldn't find authed_user when parsing the JSON for PasswordVault Field Checker.
canvas-gauge-card.js:235   CANVAS-GAUGE-CARD   Version 0.0.4    
card-mod.js:5 CARD-MOD 3.0.12 IS INSTALLED 
mini-graph-card-bundle.js?v=0.10.0:1  MINI-GRAPH-CARD  0.10.0 
utils.ts:3  BATTERY-STATE-CARD  1.6.4
button-card.js:425   BUTTON-CARD   Version 3.4.2 
scheduler-card.js:1648   SCHEDULER-CARD    Version: v2.1.4 
floorplan.js:87 Floorplan for Home Assistant (ha-floorplan)Version 1.0.25
browser_mod.js:149 BROWSER_MOD 1.3.0 IS INSTALLED    DeviceID: 2d9d213b-b7d81327
:8123/api/scheduler/edit:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
DevTools failed to load source map: Could not load content for chrome-extension://eoolfmmapnkhandljfaaofncecfakljd/dist/Versioning.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
 

### Steps to Reproduce
[Explain how to see the behaviour]

Select a schedule that turns on/off a set of lights together at one or more times during a day. Try to remove/deselect just one of the set of lights, move to next sub-page using "next" button then press "save" button.

![schedulerErrorScreenshotWithConsole](https://user-images.githubusercontent.com/3940751/131828645-ba7e7075-ea8f-49c7-9df4-a3ab49d0f689.png)

**Comment by NickInManchester** [comment] 2021-09-02 10:43
On further testing, this bug seems to only apply to schedules using a time scheme, not a simple on or off action. My scheme has a OFF zone, a single ON zone and a final OFF zone running midnight to midnight.

**Comment by nielsfaber** [comment] 2021-09-03 06:41
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/435

**Closed by nielsfaber** 2021-09-03 06:41 UTC
Labels: bug
