### ISSUE TITLE
Feature request: add support for sunrise/sunset in time scheme editor

### ISSUE THREAD

**Issue by hdejongh** [nielsfaber/scheduler-card#289] opened 2021-01-03 17:44 UTC
Hello,

would it be possible to use sunset and sunrise in the time scheme editor.
And while you are add it a randomizer for a action in a time frame.

For example:

i would like to the garden lights to turn on with a transition of 3600 at sunset and turn off with a transition of 3600 at sunrise.
I would like the living room lights to turn on with a transition of 3600 at sunset and turn off random between 23:00-23:00
Then around 7:00 in the morning they should turn on, but only if the sun has not risen yet and turn off when the sun has risen after 7:00. (maybe better to combine that with a LUX state?)

Same goes for covers. I want them closed (kids room) at sunset aslong as that is before 19:30 otherwise do it at 19:30..

ill buy you some more coffee:)

**Comment by nielsfaber** [comment] 2021-01-03 20:40
Hi Hans,
Thanks for your enthousiasm and sharing ideas for improvements!

As for:
> would it be possible to use sunset and sunrise in the time scheme editor.

Let me share a bit of background.

Currently there are two different editors in the card:
1. Single time picker, which allows fixed time and relative to sunrise/sunset (with offset up to +/- 2 hours)
2. Time scheme editor, which allows you to divide the day in timeslots (with fixed times) and pick an action for each slot.

Initially the single time picker was the only editor (it's still not in the demonstration GIF).
The time scheme editor was added later because I had the idea in mind (see [here](https://community.home-assistant.io/t/scheduler-card-custom-component/217458/24?u=neliss) the first mentioning of it) of creating a timeline with draggable segments. 

I'm not really happy with the division between them and would like to merge them into a single editor that is scalable from single action to a sequence of timeslots (or separated points).
Your use-case, a start+stop action (opening/closing the covers) is a very common one, but currently requires 2 schedules (or a time scheme, but then times are fixed).

Long story short: I have the intention to improve this.
Merging the views would automatically have sunset/sunrise available for all timeslots as well, and should allow you to set up an easy start/stop task.
The scheduler-component (backend) is already prepared for this.
The problem is that the GUI needs to be changed a lot to accommodate this. 

So it will take quite some free hours to get this in place.
Until then I'm afraid these requests cannot be fulfilled quickly (I have no idea where to add the sunrise/sunset button in the current time scheme editor).
So I hope you can bring up some patience for this 🙂 

As for:
> And while you are add it a randomizer for a action in a time frame.

I responded to this request on the forums. It should be possible, but with some help from an external script.

Regarding this:
> Then around 7:00 in the morning they should turn on, but only if the sun has not risen yet and turn off when the sun has risen after 7:00. (maybe better to combine that with a LUX state?)

There is already an open issue for it: https://github.com/nielsfaber/scheduler-card/issues/281
I see ways to make this happen, but also here I have to move some mountains before it can be made available.
For the time being: between approx. 15 march - 15 september the sunrise is before 07:00 in the netherlands, so you could manually switch them to fixed time in this period.

Regarding: 

> ill buy you some more coffee:)
 
You bought me plenty of coffees already!
Although I appreciate that a lot (if all users would buy a single coffee, i'd be a very happy man), they will not influence the priority/time I assign to feature requests.
This is and stays a little after-hours project for me.
I started this because I think HA is missing a graphical schedule tool (and many users seem to agree on this 😄 ), it got a little out of hand from there.

**Comment by emeyedeejay** [comment] 2021-01-04 06:58
A little out of hand??! Just shows how good it is that there are frequent requests for additional features etc. HA is much better for this add-on.

Just please, please reconsider the +/- 2 hours from sunrise/sunset item. I know you are anti it but there are genuine use-cases out there and having a limit such as this is unfortunate.

Thanks for all the time you put in ... off to buy you some coffee.

**Comment by nielsfaber** [comment] 2021-01-04 14:19
> Just please, please reconsider the +/- 2 hours from sunrise/sunset item. I know you are anti it but there are genuine use-cases out there and having a limit such as this is unfortunate.

Let's discuss that in https://github.com/nielsfaber/scheduler-card/issues/213

**Comment by hdejongh** [comment] 2021-01-04 14:26
can't you dynamically  show the sunrise and sundown as a coloured line clickable line in the time scheme editor?
no rush for me:)

**Comment by KTibow** [comment] 2021-01-05 02:25
Does this look good:
![image](https://user-images.githubusercontent.com/10727862/103599414-ee5e3600-4eb9-11eb-9c67-bb6281da9f74.png)
Not sure if sun vs elevation is a difference. Tooltip idea:
![image](https://user-images.githubusercontent.com/10727862/103599533-2e251d80-4eba-11eb-8c85-ac953eb22395.png)

**Comment by chasut** [comment] 2021-01-11 16:38
Came here looking to see if there was already a feature request for this; here it is.  Would love this.  Couldn't see in my head how it might work, but like the suggestion above (although I would prefer time offset v elevation as it requires to much thinking).  Also, it might be handy to be able to toggle the start/end point from sunrise to sunset.

Your integration/card is a wonderful new addition to my config, filling in a big missing piece for HA.  Thank you for your work and ingenuity.  Looking forward to see how you evolve this.  Off to buy you a coffee...

**Comment by nielsfaber** [comment] 2021-02-04 17:20
Just a heads up: I am working on this.
It will take some patience from your side still, I don't have much time available currently.

**Comment by samnewman86** [comment] 2021-03-12 20:44
Thanks for your hard work on this I'm excited to see this added functionality to an already polished component.
Have you any intention to submit this to ha as a core component? It would make so much sense for a decent scheduler like this to be built in

**Comment by nielsfaber** [comment] 2021-03-12 21:03
The reason why this functionality is not added to the card yet, is because of the issues that come with the processing of the timeslots.
E.g. i want to turn on a lamp at sunset and turn it off at 9:00 pm.
In the winter this will work fine, in the summer the sunset time could reach past 9:00 pm, so a timeslot could reach a negative duration.
Even worse, it would become overlapping with an adjacent timeslot.
The scheduler component is not really designed to handle these cases, and I don’t see an easy way to solve the issue.
I would prefer to give the user complete freedom to make whatever combination of start and stop times for a timeslot, rather than creating artificial limitations in the GUI.
If anyone can help me on a nice way to deal with these conflicts the road would be open to add the function to the card.

**Comment by chasut** [comment] 2021-03-13 15:28
Interesting.  I guess I never thought that only one endpoint would be relative.  I expected/assumed that if I set a start time relative to the sunset, that the end time would also be relative to the sunset.  Therefore the entire time slot is relative.  I personally have no use-case where I would need a fixed end point with a relative start point.

In other words.  The time slot can always be expressed with a start time and duration.  The only difference between a time slot that is relative and one that is fixed is the logic behind the calculation of the start time.  

Now if you allow the end point to be relative to something like the sun rise, then perhaps edits might be challenging for anyone above the arctic circle :)  But I am with you on the idea that it is fine for the user to bear some responsibility for their own logic.  Same, by the way, for the possibility of overlapping time slots.

Anyway, just some thoughts as you work through this.

**Comment by nielsfaber** [comment] 2021-03-13 15:53
@chasut Thanks for joining this discussion!
> I guess I never thought that only one endpoint would be relative. I expected/assumed that if I set a start time relative to the sunset, that the end time would also be relative to the sunset. Therefore the entire time slot is relative. I personally have no use-case where I would need a fixed end point with a relative start point.

I think the majority of users actually will need this flexibility. E.g.:
- Garden lights are typically to turned on from sunset to midnight.
- Shutters need to open at sunrise and close at sunset.

If I don't take it into account now, I'm sure it will be a matter of time until this feature will be requested.
So I rather walk the extra mile now to cover all scenarios.

> In other words. The time slot can always be expressed with a start time and duration. The only difference between a time slot that is relative and one that is fixed is the logic behind the calculation of the start time.

The current editor is made for defining start and stop times, not durations.
I think it will lead to a more complex GUI (more than I like) if I need to add the option of defining duration (there's actually an open PR for it).
The problem remains with the next timeslot. Timeslot A could be relative to sunrise, but timeslot B might have fixed times.
They could still eventually overlap, which is both a problem for visualization in the card as for processing by component.

> perhaps edits might be challenging for anyone above the arctic circle

I guess if you live in the top of Norway or something, you stay away from using sunrise and sunset as reference points.
If scheduler is useful for ~99% of users I'm more than happy.

I could make some "capping" function that ensures a timeslot has at least a duration of 1 minute.
Likewise, I could also make a limit that prevents a time like "5 hours after sunset" to shift to a next day (so 23:59 max).
I think this should solve most problems (at least what I can foresee), but timeslots will get squeezed together to an extend that they become hard to select in the editor.

**Comment by chasut** [comment] 2021-03-13 16:27
I would certainly welcome the opportunity to adapt my current automations over and put it through it's paces.  This approach, while different than what I do today, offers more flexibility in the long run.  I certainly understand the challenges it creates for the logic and UI but think your proposed basic editing is sound and in any case start with simple and expand as users provide feedback on applicability to their specific use cases.  

Thank you for spending your time on this card/integration, absolutely love it.  I will leave you to work your magic and or others to weigh-in.

**Comment by derekoharrow** [comment] 2021-04-14 08:37
Just wanted to add my support for this idea and perhaps a couple of thoughts too. 

I agree that we really need both sunrise/sunset and time of day together - eg turn on TV an hour before sunset and off around 23:30 to emulate someone being home. 

In terms of how to deal with start time coming after end time during the summer (or vice versa in winter), is it possible to check when creating the scheme and just pop up a warning message? I’m sure there must be a source of earliest/latest sunrise/sunset info out there that could be used based on your servers lat/long. And perhaps in the case that does happen, is it possible to just skip the earlier (in order) entry in the scheme?

Or, is there some way to use the conditions instead - eg have a scheme that runs from 18:00-23:00 but use conditions to start it an hour before sunset. That way can you avoid the issue of overlapping times?

**Comment by nielsfaber** [comment] 2021-04-14 08:47
@derekoharrow I agree it should come, it is taking too long. 

> I’m sure there must be a source of earliest/latest sunrise/sunset info out there that could be used based on your servers lat/long. And perhaps in the case that does happen, is it possible to just skip the earlier (in order) entry in the scheme?

IMO this is quite complicated and doesn't fit with the card, and also is not a responsibility for the card to validate this. 

> Or, is there some way to use the conditions instead - eg have a scheme that runs from 18:00-23:00 but use conditions to start it an hour before sunset. That way can you avoid the issue of overlapping times?

Conditions are not used for controlling the times where a schedule may trigger, only defines "rules" which needs to pass (upon triggering) for executing the action. 

In the meantime I made some changes in the backend so it will prevent timers to pass the 00:00/24:00 limit due to sunset shift.
Timeslots with a negative duration will simply be treated as a simple timer (so are only active for a moment defined by the start point).
The only step left is to make a good GUI for this.

**Comment by derekoharrow** [comment] 2021-04-14 08:59
> @derekoharrow I agree it should come, it is taking too long.

Thank you. We appreciate you are doing this in your spare time, so whenever it comes we will be happy! It's great to have good developers like you who are willing to spend their own time for our benefit.


> > Or, is there some way to use the conditions instead - eg have a scheme that runs from 18:00-23:00 but use conditions to start it an hour before sunset. That way can you avoid the issue of overlapping times?
> 
> Conditions are not used for controlling the times where a schedule may trigger, only defines "rules" which needs to pass (upon triggering) for executing the action.

I was just thinking this could be a good interim solution. So, you have a schedule, such as 18:00-23:00, but then use conditions to control the action within that time frame. For example, a condition of after sunset. I guess you could do this using template boolean sensors - have a template boolean that is on 1 hour before sunset, and then use that in your conditions, but between those two times. Could this work? Are conditions only evaluated at the start of the time period, or constantly throughout it?

> The only step left is to make a good GUI for this.

Thank you!!

**Comment by Chronocento** [comment] 2021-05-26 09:56
Came to suggest this feature, and found that you are already working on it! Great!
Have you had the chance to develop it further?

**Comment by nielsfaber** [comment] 2021-05-26 16:39
@Chronocento I am not working on this currently.
The main reason is that I don't see a way to integrate it with the time slot bar.
The user should be able to define for each interval in the bar if it has a fixed time or dependent on sunrise/sunset. 
Currently the user only has the option to move the time.

**Comment by mosesrenegade** [comment] 2021-08-31 19:16
Quick question, is there any movement on the +/- 2 Hour limit I know it was addressed in #213 however I did not see a resolution. The reason I ask is that I control my blinds in the rear of the house with the scheduler. The sunset times constantly move where I am over the course of the year. It gets fairly hot in the back and so right now by the time I put the shades down -2 before sunset it already is too hot in the back of the house. -3 would be nice. Specifically in the summer. Right now it's not so workable. with -2. Right now I have a silly -2 for shades down and -1 for shades up but that really isn't a good solution. What would be preferable would be -4 for shades down and -1 for shades up (or -.5). I know its a silly ask and I could maybe tweak a couple of internal bits, but just curious.

**Comment by emeyedeejay** [comment] 2021-11-09 05:52
Just checking in on this one... Looks like you are thinking about it - excellent ... thank you.

**Comment by nielsfaber** [comment] 2021-12-09 10:06
This feature is finally finished. 
I apologize for the huge delay on this feature, and thank you for your patience.

The markers between the timeslots are now selectable and once selected you can change between fixed time/relative to sunrise/relative to sunset.

Example:
![image](https://user-images.githubusercontent.com/16861605/145373172-fb5ec8cb-b6a6-4767-88e1-035defe0e00a.png)

Note that the sunrise/sunset modes are only available with a maximum of 2 hours offset (same as the other time picker).
I am doing this to reduce the risk of creating a time scheme that doesn't make practical sense or will get corrupted over time.
Corruption might occurs in the following circumstances:
1. Time might move to a previous or next day (e.g. 4 hours after sunset could move beyond midnight in the summer)
2. Duration of a timeslot could become negative due to shift of the sunrise/sunset time
3. Timeslots may become overlapping if some depend on fixed times and others on sun

The backend (scheduler-component) has been adapted to be capable of dealing with these corruptions. 
The frontend (scheduler-card) will make alterations (in an attempt to solve the corruptions) when the user edits an existing schedule, in order to display it correctly in the GUI. The user is responsible to review the scheme and save it if the changes are OK.

If you experience problems with the new feature, please open a new issue to address it.

**Closed** 2021-12-09 10:06 UTC
Labels: feature_request, will pick this up at some point

**Comment by KTibow** [comment] 2021-12-11 00:39
wait what
you actually did this!
nice :clap:

**Comment by emeyedeejay** [comment] 2021-12-11 11:50
FANTASTIC!!!!! Thank you for getting to this! It may not seem like a worthwhile item to you but I can finally use your scheduler as I want to be able to

![image](https://user-images.githubusercontent.com/8543879/145675352-26daa3cc-233d-455a-bf17-76cea3485960.png)

Note to other readers - the above is setup in the scheduler.storage file in the .storage folder which is hidden. Install the SAMBA add-on and access the HA files from that.

![image](https://user-images.githubusercontent.com/8543879/145675434-e7ececb2-5c3d-41c1-a09e-9f7e459244bf.png)

**Comment by nielsfaber** [comment] 2021-12-11 12:06
> FANTASTIC!!!!! Thank you for getting to this! It may not seem like a worthwhile item to you but I can finally use your scheduler as I want to be able to

You're welcome! I
 am not particularly proud of pushing forward this request for up to 11 months now, but at the end quite some things had to be changed to accommodate this.

Honestly I thought you would start to hate me for sticking to the 2 hours sunrise offset limit 😅 
I would like your thoughts on the 'corruption' concerns I see, this is the only thing holding me back from giving the freedom to the user (the backend will gracefully handle these cases now, worst-case result is that wrong input leads to no actions occuring).

**Comment by emeyedeejay** [comment] 2021-12-11 12:14
Hate you? LOL! No way - was always just frustrating that I could never use such an awesome add-on exactly the way I wanted to... If anything I'm being selfish!

I did notice some GUI corruption when playing around with it - the time period sort of split across 2 lines - I'll see if I can reproduce.

I think the only way you will be able to truely deal with this without corruption and possible crazy cases would be for your timeline in the GUI to not represent 1 day. It could default to 1 day but maybe have clickable time sliders to say actually ... I want to see 3 days and then create my scheme on that timeline. Just thinking out loud.
