### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Misiu** [nielsfaber/scheduler-card#385] opened 2021-05-06 13:23 UTC
This error appeared today after updating to 2021.5.0.

> Logger: homeassistant
> Source: core.py:1428
> First occurred: 12:54:17 (1 occurrences)
> Last logged: 12:54:17
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/scheduler/actions.py", line 188, in async_entity_changed
>     await self.async_process_queue()
>   File "/config/custom_components/scheduler/actions.py", line 234, in async_process_queue
>     res = await self.async_execute_action(action, conditions, condition_type)
>   File "/config/custom_components/scheduler/actions.py", line 278, in async_execute_action
>     await async_call_from_config(
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 165, in async_call_from_config
>     await hass.services.async_call(**params, blocking=blocking, context=context)
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1428, in async_call
>     raise ServiceNotFound(domain, service) from None
> homeassistant.exceptions.ServiceNotFound: Unable to find service input_boolean.turn_on

**Comment by crazyfx1** [comment] 2021-05-06 16:31
Same issue with input_number:

```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 18:05:18 (1 occurrences)
Last logged: 18:05:18

Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('aafa66',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 191, in async_timer_updated await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 194, in async_queue_actions await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 234, in async_process_queue res = await self.async_execute_action(action, conditions, condition_type) File "/config/custom_components/scheduler/actions.py", line 278, in async_execute_action await async_call_from_config( File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 165, in async_call_from_config await hass.services.async_call(**params, blocking=blocking, context=context) File "/usr/src/homeassistant/homeassistant/core.py", line 1428, in async_call raise ServiceNotFound(domain, service) from None homeassistant.exceptions.ServiceNotFound: Unable to find service input_number.set_value
```

**Comment by nielsfaber** [comment] 2021-05-06 16:38
This is a race condition, apparently scheduler is initialized earlier than the HA helper entity platforms.
I patched this issue already, but there is no release made for this yet.
You could make a checkout from the scheduler-component repo to have it fixed.
I will make sure to push out a release soon.

Duplicate of https://github.com/nielsfaber/scheduler-component/issues/104.

**Closed by nielsfaber** 2021-05-06 16:38 UTC
