### ISSUE TITLE
not possible to generate a task properly the buttons are going crazy on HA 2022.9.4

### ISSUE THREAD

**Issue by moshiko2312** [nielsfaber/scheduler-card#603] opened 2022-09-16 19:24 UTC
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.6

### Component Version

v3.2.10

### Bug description

It is not possible to generate a task properly the buttons are going crazy
[test.webm](https://user-images.githubusercontent.com/48163773/190715181-a9c3adbc-b6c1-4fa4-aa8e-f9ab49aa183d.webm)

### Steps to reproduce

Just creates a new task

**Comment by chrugel** [comment] 2022-09-16 21:19
Hi,
I think i might have the same issue?
Same Card and Component Version.

https://user-images.githubusercontent.com/1814197/190757641-4ec0a9ef-fb6d-4a9e-b6e1-b53b5aa4ee95.mp4

**Comment by tschut** [comment] 2022-09-17 14:15
This is the same issue as #602 and #601

**Comment by nielsfaber** [comment] 2022-09-17 14:25
Duplicate of #601

**Closed by nielsfaber** 2022-09-17 14:25 UTC
Labels: bug

**Comment by moshiko2312** [comment] 2022-09-18 11:00
Ok thanks for all🙏
