### ISSUE TITLE
Feature Request: Sunrise/Sunset with option latest

### ISSUE THREAD

**Issue by tsvsj** [nielsfaber/scheduler-card#336] opened 2021-02-18 11:14 UTC
Hi,

thanks for this great add-on for HA! This is really awesome!

I'm currently missing the option to specify the option `latest` along with sunset/sunrise. To be honest, I'm missing this in HA in general or couldn't find a way yet to achieve this. Usually I define the latest time, at which my action should be fired. Especially during the summer time, for the roller shutters in the children rooms, it's necessary to define an earlier time than sunset, to close the covers. For now I wasn't able to find convenient way to achieve this in HA, without coding it by myself. It would be great, if that feature would be available!

Regards

**Comment by nielsfaber** [comment] 2021-02-18 11:36
Duplicate of #281

**Closed by nielsfaber** 2021-02-18 11:36 UTC
