### ISSUE TITLE
Allow entities of domain "number" to be included

### ISSUE THREAD

**Issue by srodighiero** [nielsfaber/scheduler-card#508] opened 2022-01-21 14:35 UTC
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

Allow entities of domain "number" to be included to be controlled and (possibly) as condition.

In my particular case, I have an irrigation valve custom setup via Local Tuya integration. The valve has a percentage open state, that I can only control via a "number" entity, and no "toggle" or "switch" control

### Additional info

The control and condition should allow to set a nr (better if based on the mode of the entity itself, like slider or numeric)

**Comment by nielsfaber** [comment] 2022-01-22 17:43
OK, no problem, will pick it up when I can

**Comment by nielsfaber** [comment] 2022-01-25 20:08
Release v2.3.1 is out which contains this feature.
 Please test it and close the issue if your request is fulfilled, otherwise let me know.

**Comment by srodighiero** [comment] 2022-01-26 15:39
Hi @nielsfaber,

I see. In any case I just tried as test to use them in options, but seems not working, there is no way to set a value:
![image](https://user-images.githubusercontent.com/4833164/151195239-1fecf4a8-0ed8-43b8-9b9c-071bf9bc9f12.png)

**Comment by nielsfaber** [comment] 2022-01-27 06:00
I'm sorry about this. I will try to test using it in conditions myself and also add them as actions.
It should work the same as input_number but seeing NaN is not a good thing..

**Comment by srodighiero** [comment] 2022-01-27 10:29
no worries @nielsfaber, and thank you for the effort. Let me know if I can help you in any way.

**Comment by nielsfaber** [comment] 2022-01-28 19:12
I just release v2.3.2.
Please update and test if the problem is solved now, you can close the issue if so.

**Comment by srodighiero** [comment] 2022-01-31 10:48
Thanks Niels, seems ok now.

I'm just wondering if you could implement to set different values/state for "multiple" selection.
Example: in my case the two entities have 2 different "scale":
- "Controllo flusso" is a % from 0 to 100
-  "Durata flusso" is a timer, that has a mx value of 10min (600sec)
![image](https://user-images.githubusercontent.com/4833164/151780527-8344b3f2-e459-4013-ad7a-bb3a8be5e54b.png)

**Comment by nielsfaber** [comment] 2022-01-31 10:53
Thanks for confirming 👍 

> I'm just wondering if you could implement to set different values/state for "multiple" selection.

No, you have to create separate schedules for this.
A schedule cannot be used to execute multiple actions at a single time, it would create very difficult situations to visualize in the card (users could ask to operate a heater together with a lamp etc.).
You can only select multiple entities in case they have the actions in common (e.g. for turning on multiple lights).
If you want to execute multiple tasks with a single schedule, you have to create a sequence in a script, and trigger the script from scheduler instead.

**Closed by nielsfaber** 2022-01-31 10:53 UTC
Labels: in development, feature_request
