### ISSUE TITLE
Present optional name of schedule item everywhere the schedule item is listed

### ISSUE THREAD

**Issue by Bazmundi** [nielsfaber/scheduler-card#484] opened 2021-12-04 05:47 UTC
### Checklist
- [*] I checked for similar existing requests (both open and closed) before posting.
- [*] My request is generic, other users may benefit from it too.

### Proposal
[clear description of what you want to see changed or added]

Since we can optionally add a name to schedule entry, can we get that optional name to turn up as the schedule entry name please? 

  
### Additional info
[some example of how the new functionality should look like]

While the schedule item name appears in logs, its needed in the list of schedule items, since multiple items could have same script or entity associated with the entry, so making it confusing because multiple items can have the same name in the list.

**Comment by nielsfaber** [comment] 2021-12-04 09:34
Duplicate of #455

**Closed by nielsfaber** 2021-12-04 09:34 UTC
